### ISSUE TITLE
having trouble on debian

### ISSUE THREAD

**Issue by jedahan** [zellio/pdf2laser#3]
What are the build instructions? I've been randomly running autoconf, autoreconf, libtoolize, etc but nothing can find gsapi_* even though I have libgs-dev installed.

**Comment by zellio** [comment]
I'm working on updating the companion pdf2laser-debian repo which provides packaging for this application. 

I had success building for Debian stable via 

```
apt install --no-install-recommends git ca-certificates make autoconf automake clang libtool libgs-dev 
make -f Makefile.dist
./configure --prefix=/usr --sysconfdir=/etc
make install 
```
Which version are you trying to use?

**Comment by jedahan** [comment]
```
Package: libgs-dev
Version: 9.50~dfsg-5
```

**Comment by zellio** [comment]
The build files don't explicitly list the ghostscript library as a dependency so debian isn't picking it up on compile.

I'll push a fix for this this weekend. Thanks for catching it.

**Comment by zellio** [comment]
New version 0.5.1 should fix this issue
